### ISSUE TITLE
Right-Cerebral-White-Matter is green in FreeSurferColorLUT.txt

### ISSUE THREAD

**Issue by jennydaman** [niivue/fs2NiiVueColormaps#2]
![image](https://github.com/niivue/fs2NiiVueColormaps/assets/20404439/1b59c3e7-521d-4e9c-a687-1fb3c554129f)

not sure why it's green...

**Comment by neurolabusc** [comment]
@jennydaman well spotted. This [repository](https://github.com/niivue/fs2NiiVueColormaps/blob/14ea4963b8477b7c94bb6034f3e3229d74dbbbb8/FreeSurferColorLUT.txt#L46C1-L46C58) copies the values from [AFNI](https://github.com/afni/afni/blob/082d1336256635faaa5e65cd69abda988c8b5cbe/src/text_install/afni_fs_aparc%2Baseg_2000.txt#L23) and the [FreeSurfer sample_colors](https://github.com/freesurfer/freesurfer/blob/1feb6a6862bffff3a70152b008ccab3bee1dc869/distribution/sample_colors#L42)  rather than the [FreeSurferColorLUT](https://github.com/freesurfer/freesurfer/blob/1feb6a6862bffff3a70152b008ccab3bee1dc869/distribution/FreeSurferColorLUT.txt#L45) that matches my copy of FreeSurfer. Perhaps @pwighton and @mrneont
can provide insight. Perhaps just trying to remind users of left versus right to avoid confusion regarding neurological or radiological convention.

**Comment by pwighton** [comment]
`freesurfer/distribution/sample_colors` [hasn't been updated in 21 years](https://github.com/freesurfer/freesurfer/commits/1feb6a6862bffff3a70152b008ccab3bee1dc869/distribution/sample_colors) except for a global search/replace 5 years ago.

The README states that `Freesurfer-LUT.txt` comes from PyROI which [hasn't been updated in 14 years](https://github.com/mwaskom/PyROI/commits/master/)

It looks like the color changed from green to white somewhere between v5.3.0 and v6.0.0.

I suggest removing `Freesurfer-LUT.txt` and replacing `FreeSurferColorLUT.txt` with [`freesurfer/distribution/FreeSurferColorLUT.txt`](https://github.com/freesurfer/freesurfer/blob/dev/distribution/FreeSurferColorLUT.txt) for various versions of FreeSurfer.

I've opened a PR that does that.

**Comment by neurolabusc** [comment]
@mrneont are you OK with me updating the NiiVue freesurfer color map so the right cerebral white matter is white not green, or will this degrade our support for AFNI?

**Comment by mrneont** [comment]
Hi, @neurolabusc : I am certainly fine with that.  We don't actually make use of the color values in that file.  They were just ported along from the original FreeSurfer text file from which we had based it.  It should be fine for us to just update what is there, I would guess, since it won't affect anything at present on our end.

I am surprised that there are different color lookup values for the same region.  But thanks, @pwighton, for explaining a bit about the trajectory of files. We have had this text file for a while, so I suspect it was simply just based on the older version.
